### PR TITLE
New term requests

### LINKED ISSUE #435: NTR: Bag and mask resuscitation performed
For new term requests, please provide the following information:
**Term Label** Bag and mask resuscitation performed

**Synonyms** [optional]

**Definition** Multifilter value indicating if an infant had bag and mask resuscitation performed soon after birth

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
- [x ] Information (generically dependent on some artifact and stands in relation of aboutness to some entity, such as data, identifier, document)

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Sheena, for ClinEpiDB

### LINKED ISSUE #506: NTR: Regenerating family member 1 beta
For new term requests, please provide the following information:
**Term Label** [required]
Regenerating family member 1 beta

**Synonyms** [optional]

**Definition** [required except for organism name]
The definition should be understandable even for non-specialists. Include a PubMed ID or DOI to refer to any relevant article that provides additional information about the suggested term.
Same as http://purl.obolibrary.org/obo/EUPATH_0036337 except assayed on a maternal stool specimen

**Suggested Parent Term** [required]
Please look in the ontology hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/eupath) or choose one from following list: 
- [ ] Material (independent of other entities and can be maintained through time, such as person, cell, sample)
- [ ] Process (has temporal proper parts and for some time depends on some material entity, such as life cycle, cell division, heart beating, sleeping)
- [ ] Information (generically dependent on some artifact and stands in relation of aboutness to some entity, such as data, identifier, document)
- [ ] Characteristic/Quality (inheres in or is borne by other entities, such as height, color, disease)

Characteristic

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Please indicate which resource/database/project/ request the term.
ClinEpiDB

### PR DESCRIPTION
**Pull request by johnwjudkins**
Resolves #435, #437, #438, #439, #440, #441, #445, #446, #451, #491, #492, #493, #496, #497, #498, #499, #500, #501, #502, #503, #508, #510, #513, #519, #520, #521.

This should resolve all term request issues by Sheena, except for some maternal assay data terms (which I will add in a separate PR based on the new design pattern) and #495 (I had a question about multifilter terms, which I added to the meeting agenda).

This resolves partially #506, which will be fully resolved when I add maternal assay data terms.

### CODE REVIEW

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/445:
EUPATH:0025175
label: categorical duration since bed net treatment
The term is not added and the ID is wrong. It should be EUPATH_0025174 not EUPATH_0025175

https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/496
EUPATH:0060125 Label: second antibiotic in treatment EUPATH:0050504
Label: first antibiotic in treatment
Logic axiom is not added as it indicated in the issue tracker.


Please indicate the term ID, label, and definition added in the ontology in the following issue trackers:
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/497
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/498
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/499
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/502
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/503

Found a term without label and definition:
http://purl.obolibrary.org/obo/EUPATH_0011277
We may remove it and add in with other organism detection assay and result terms.

**Comment by johnwjudkins** [comment]
I'll go ahead and add the annotations for http://purl.obolibrary.org/obo/EUPATH_0011277 here. Issue trackers are updated and requested changes are made.

**Comment by johnwjudkins** [comment]
However, I am leaving out EUPATH:0011748 for now, because I will add it later in an assay template.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
EUPATH:0025174
label: categorical duration since bed net treatment
in https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/445

And the term 
EUPATH:0025175
label: categorical time of bed net ownership
in https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/446

merged to one term. 

I cannot find 'categorical duration since bed net treatment'. The 'categorical time of bed net ownership' is in with wrong IRI and definition.

**Review by zhengj2007 — COMMENTED** [review]
The term, EUPATH:0025175, is added with label 'categorical duration of bed net ownership' different from the one (categorical time of bed net ownership) indicated in the issue tracker. If it is the label we'd like use, please update the label in the issue tracker. 

All other terms look good.

**Comment by johnwjudkins** [comment]
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/446#issuecomment-1518324259

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
