### PR TITLE
collection start & end date terms

### LINKED ISSUE #465: NTR: start and end date terms for popbio collections
**Background** several popbio datasets have specimen collections with either date ranges ("May to July 2010") or multiple dates ("2002, 2004, and 2005") or both.  Also as in the examples, the dates are incomplete and refer to whole months and/or years.

Currently the date fields in EDA can't handle ranges or incomplete dates...

We may develop a DateRange field type for EDA (in addition to Number, Date and String) in the future, but for now here is a plan

1. create new variables for the specimen collection entity:
    - specimen collection start date : YYYY-MM-DD
    - specimen collection end date : YYYY-MM-DD
    - specimen collection dates are discontinuous : Yes | No
2. convert the potentially multiple and incomplete dates into an overall start and end date (first two variables) and figure out if there any gaps in the date ranges (then the third variable will be Yes)
3. store the raw multiple date/range string (semicolon delimited) in the existing variable: OBI_0001619

**Term Label**

- specimen collection start date
- specimen collection end date
- specimen collection dates are discontinuous

**Definition** 

- A time measurement datum that is the measure of the time when the specimen collection started
- A time measurement datum that is the measure of the time when the specimen collection ended
- Information that the collection process was not continuous for the entire period between start and end dates

**Suggested Parent Term**

http://purl.obolibrary.org/obo/IAO_0000416

**Requester**
Bob/VectorBase/PopBio

### PR DESCRIPTION
**Pull request by johnwjudkins**
Resolves #465.

### CODE REVIEW

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
Parent of 'date specimen collection started', 'date specimen collection ended' and 'indicator of specimen collection date discontinuity' were set as itself. Should be subclass of 'specimen collection time measurement datum' for first two and ICE for the last one.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
'date specimen collection started', 'date specimen collection ended' might be  the subclass of 'specimen collection time measurement datum'. If so, the textual definition need to be updated as well.

**Comment by johnwjudkins** [comment]
'specimen collection time measurement datum' has the same axiom as 'date specimen collection started'. Both are defined axiomatically as being about the _start_ of the collection process. OBI has no term for information about the end of a specimen collection process.

**Comment by zhengj2007** [comment]
The term was added for NIAID GSCID-BRC metadata standard. The reason we add it because we want to indicate the time is the start point of a specimen collection for a specific specimen. 

I think the terms we created here seem not for a single specimen process. It is for a study that need to collect multiple specimens. And it will be the time for first specimen collected to the time of the last specimen collected. So, we may modify the definition, such as, A specimen collection time measurement datum that specifies the date of the first specimen collected in a study. And the logical axiom is 'is about' some 'specimen collection process'. Might ask Bob to review it before adding the term.

**Comment by johnwjudkins** [comment]
@zhengj2007 Ready for review.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
most of the terms added missing following annotations:
- definition source
- term editor/dc:contributor (both person name and ORCID if available) [Please give credit to all people who work on the terms here]
- term tracker item
- ontology term requester

Also not commit build directory that contains robot.jar

**Comment by johnwjudkins** [comment]
> most of the terms added missing following annotations:
> 
> * definition source
> * term editor/dc:contributor (both person name and ORCID if available) [Please give credit to all people who work on the terms here]
> * term tracker item
> * ontology term requester
> 

For the 3 terms I added here, none of those annotations are present. Do I need to change something there?
> Also not commit build directory that contains robot.jar

I didn't commit robot.jar. I don't see it when I click on the "Files changed" tab at the top of this page.

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
