### PR TITLE
Added assay template/module

### PR DESCRIPTION
**Pull request by johnwjudkins**
The are assay terms that could be introduced to OBI. We still need to resolve dual parenthood of children of 'clinical laboratory test' for terms in this template.

### CODE REVIEW

**Review by cstoeckert — COMMENTED** [review]
Unclear about the addition of all the properties in obi_import.owl. Is that intended/ desired?
Also not sure about:
-       <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/ontology-metadata.owl"/>
 +       <owl:imports rdf:resource="http://purl.obolibrary.org/obo/eupath/dev/assays.owl"/>

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
It seems the import_OBI.owl file did not regenerated using the 'make imports' but directly using OntoFox tool. So, it missed one step that will generate the base file from OntoFox output file using Robot tool. So, it included the specification of many terms that defined in OBI, such as IAO, UO terms.

I wrote the wiki page regarding it: 
https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/wiki/Update-import-OWL-files-using-OntoFox

In eupath_dev.owl, we import ontology-metadata.owl using:
<owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/ontology-metadata.owl"/>

I just realized that the OMO ontology is ready for use now. We'd change to 
<owl:imports rdf:resource="http://purl.obolibrary.org/obo/omo.owl"/>

**Comment by zhengj2007** [comment]
> Unclear about the addition of all the properties in obi_import.owl. Is that intended/ desired?
> Also not sure about replacing <owl:imports rdf:resource="[http://purl.obolibrary.org/obo/iao/ontology-metadata.owl"/>](http://purl.obolibrary.org/obo/iao/ontology-metadata.owl%22/%3E) with <owl:imports rdf:resource="[http://purl.obolibrary.org/obo/eupath/dev/assays.owl"/>](http://purl.obolibrary.org/obo/eupath/dev/assays.owl%22/%3E)

The eupath_dev.owl added <owl:imports rdf:resource="http://purl.obolibrary.org/obo/eupath/dev/assays.owl"/>.
The <owl:imports rdf:resource="http://purl.obolibrary.org/obo/iao/ontology-metadata.owl"/> showed deleted and then added in the modified OWL file likely due to the line changes. So, should be fine.

**Comment by johnwjudkins** [comment]
This time I used `make imports`, which only grabs the 'specifies value of' relation and the 'temperature value specification' class in addition to 'temperature measurement assay'.

My most recent commit replaces IAO as a metadata resource with OMO, as Jie suggested.

**Review by zhengj2007 — APPROVED** [review]
Looks good to me.

**Review by cstoeckert — APPROVED** [review]

**Pull request merged**
