### PR TITLE
Issue# 142

### PR DESCRIPTION
**Pull request by zhengj2007**
Summarize terms in the ontology
Provide proposed labels for some ICE terms, issue: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/142

### CODE REVIEW

**Review by cstoeckert — COMMENTED** [review]
Looks good but I have questions about the PopBioIDs. Do these need to be synchronized across sheets? Is the PopBio sheet meant to be the new 'master PopBio' sheet? If so need to get Bob M.s OK.

**Review by johnwjudkins — COMMENTED** [review]
I suggest the label for EUPATH:0021047 be 'indicator of whether forgot treatment location within past year'. If that change is made along with Chris's suggestion to add "whether" to the labels, then I approve.

**Comment by zhengj2007** [comment]
> I suggest the label for EUPATH:0021047 be 'indicator of whether forgot treatment location within past year'. If that change is made along with Chris's suggestion to add "whether" to the labels, then I approve.

Added "whether" to the labels began with 'indicator of'. 
Added 'participant' to suggestted EUPATH:0021047 label for consistent with the definition as 'indicator of whether participant forgot treatment location within past year'.

**Comment by zhengj2007** [comment]
> Looks good but I have questions about the PopBioIDs. Do these need to be synchronized across sheets? Is the PopBio sheet meant to be the new 'master PopBio' sheet? If so need to get Bob M.s OK.

The PopBioIDs added according to latest 'master PopBio' sheet I downloaded from Google and map based on the OBO ontology term IDs in the sheet. We have some of them indicated in the VEuPathDB ontology but not all. Need to decide whether we want to keep PopBioIDs in the ontology.

**Review by cstoeckert — APPROVED** [review]

**Review by johnwjudkins — APPROVED** [review]

**Review by johnwjudkins — CHANGES_REQUESTED** [review]
The label for EUPATH_0010418 is
'indicator of whether participant eligibility for enrollment'
It should be
'indicator of whether participant eligible for enrollment'.
Everything else looks good.

**Comment by zhengj2007** [comment]
> The label for EUPATH_0010418 is
> 'indicator of whether participant eligibility for enrollment'
> It should be
> 'indicator of whether participant eligible for enrollment'.
> Everything else looks good.

relabelled the term per request

**Review by johnwjudkins — APPROVED** [review]

**Pull request merged**
