### PR TITLE
Replacing arthropod placeholder terms w/new NCBITaxon terms

### LINKED ISSUE #216: Import new arthropod terms from NCBITaxon
These are from the latest NCBITaxon release and will replace some of the placeholder terms created for #105.

http://purl.obolibrary.org/obo/NCBITaxon_2761511 Aedes ledgeri
http://purl.obolibrary.org/obo/NCBITaxon_2785382 Anopheles franciscanus
http://purl.obolibrary.org/obo/NCBITaxon_2563468 Culex aurantepex
http://purl.obolibrary.org/obo/NCBITaxon_1678250 Culex rubinotus
http://purl.obolibrary.org/obo/NCBITaxon_1481111 Culex stigmatosoma
http://purl.obolibrary.org/obo/NCBITaxon_2563599 Mimomyia mediolineata
http://purl.obolibrary.org/obo/NCBITaxon_2563597 Mimomyia mimomyiaformis

### PR DESCRIPTION
**Pull request by johnwjudkins**
Closes #216

### CODE REVIEW

**Review by zhengj2007 — COMMENTED** [review]
Replacement looks good to me.

Reminder to update some related documents:
1) Indicate which term IRI replaced in the tracker: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/105

2) Update PopBio mapping worksheet if need

**Review by cstoeckert — CHANGES_REQUESTED** [review]
If importing new terms, the EUPATH terms that they are replacing should just be deprecated - not scheduled for deprecation.  
A separate question is why the value for 'scheduled for obsoletion on or after' is YES instead of a date or release.

**Comment by cstoeckert** [comment]
Agree to create an obsolete.tsv file (as per OBI) and put the EUPATH terms there with appropriate annotations indicating replacement terms.

**Comment by johnwjudkins** [comment]
I noticed Aedes ledgeri is not in the .owl file - this is because the ontozoo is not using the latest NCBITaxon release. (I asked Oliver to update.) I'll make this a draft for now.

**Comment by johnwjudkins** [comment]
These commits fix the conflict and update schedule_deprecate to remove terms that are already deprecated. Our term for red blood cell specimen is deprecated in this branch; the matching term in OBI is added in the obi-move branch.

**Review by zhengj2007 — APPROVED** [review]

**Review by cstoeckert — APPROVED** [review]

**Pull request merged**
