### PR TITLE
Imports VEuPath terms added to OBI & deprecates those terms in VEuPath

### PR DESCRIPTION
**Pull request by johnwjudkins**
#165

### CODE REVIEW

**Review by zhengj2007 — COMMENTED** [review]
Need to specify parent of http://purl.obolibrary.org/obo/NCBITaxon_2157 #Archaea, after import the term is subClassOf NCBITaxon_1 'root'.

**Review by zhengj2007 — APPROVED** [review]

**Review by cstoeckert — APPROVED** [review]

**Comment by johnwjudkins** [comment]
Minor adjustments made - re-requesting review.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
The obsolete.owl cannot be parsed:
org.semanticweb.owlapi.rdf.rdfxml.parser.RDFParserException: [line=2604:column=172] Cannot answer characters when object properties are expected.

Need to fix.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
Four annotation properties, such as EuPathDB definition, column order, were set 'scheduled for obsoletion on or after' as Yes (may consider using boolean value). But specified as class in schedule_deprecate.owl. Need to fix.

**Review by zhengj2007 — APPROVED** [review]

**Review by cstoeckert — APPROVED** [review]

**Pull request merged**
