### PR TITLE
Modify imports

### PR DESCRIPTION
**Pull request by zhengj2007**
1. Split the OBO_input.txt based on ontology prefix to make each input file only contain one ontology for OntoFox retrieving
2. Generated the base file based on OntoFox output to avoid inconsistency due to import same terms from different ontologies
3. Removed NIAID-GSC-BRC.owl import.
4. Imported Full BFO class only and OMO ontologies
5. Updated Makefile that can update import files using command 'make imports'

Issue: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/170

### CODE REVIEW

**Comment by johnwjudkins** [comment]
I agree with the changes overall; I noticed a few issues:

Object properties from OBI and RO (including object properties with BFO IDs) and the data property OBI_0001937 need to be added to the input .txt files.
This brings in many new terms from IAO and geneontology.org that we don't use - we may want to MIREOT IAO terms.
Some OBI terms dropped e.g. terms mentioning culture medium (but do we need these?).
OBI terms are also missing axioms that are in the current release (possibly due to aforementioned missing object properties).
'ribonucleic acid' CHEBI:33697 needs to be added back.
Importing all BFO terms brings back object and 'object aggregate', which we don't use.

**Comment by johnwjudkins** [comment]
This fixes most of the issues. I think we need to fix CHEBI imports - using computed intermediates creates multiple inheritances (see 'vitamin D' parent hierarchy) and pulls in an excess of terms like 'main group molecular entity'. However, I think importing 'chemical entity' is fine (the term itself is meaningful even though I don't agree with the definition).

**Comment by zhengj2007** [comment]
I have tried to change the ChEBI imports using computed intermediates. It imports many terms we don't need and many terms have multiple parents. So, I keep how we did it before. But I am fine to change using computed intermediates import option.

**Comment by johnwjudkins** [comment]
I suggest adding these lines to input_CHEBI.txt, in the section [Top level source term URIs and target direct superclass URIs]:

http://purl.obolibrary.org/obo/CHEBI_27300 #vitamin D
subClassOf http://purl.obolibrary.org/obo/CHEBI_23367 #molecular entity
http://purl.obolibrary.org/obo/CHEBI_4822 #ergometrine
subClassOf http://purl.obolibrary.org/obo/CHEBI_23367 #molecular entity
http://purl.obolibrary.org/obo/CHEBI_50211 #retinol
subClassOf http://purl.obolibrary.org/obo/CHEBI_23367 #molecular entity

(I would change these myself, but I don't want our work on the file to conflict.)

**Comment by cstoeckert** [comment]
DIscussed and ready to merge. Will make more changes after the merge (like John's suggested ChEBI changes).

**Pull request merged**
