### PR TITLE
Axiom changes

### PR DESCRIPTION
**Pull request by johnwjudkins**
#182. I mentioned adding the placeholder EUPATH:0015669 'information on diarrhea treatment' but didn't mention a definition. I define it here as "A treatment information that mentions a medication that treats diarrhea."

### CODE REVIEW

**Review by zhengj2007 — COMMENTED** [review]
EUPATH:0015669
with axiom: (mentions some ('is substance that treats' some diarrhea))
 and ('has role' some 'medication role')

Shall we simplify it as:
(mentions some ('medication material' and 'is substance that treats' some diarrhea))

OBIB 'medication material' = ‘material entity’ and has_role some 'medication role'

-----------------
EUPATH:0010378
With update on the axiom, shall we remove ‘given to a participant under investigation’ from the textual definition?

**Review by cstoeckert — COMMENTED** [review]
I agree with both of Jie's comments.

**Review by cstoeckert — COMMENTED** [review]
We should use http://purl.obolibrary.org/obo/OGMS_0000148 instead of the one from OBIB.
It's not in Ontobee but is in OLS.

**Comment by johnwjudkins** [comment]
That IRI is for 'medication role' (not 'medication material'). We could still use that IRI, but it wouldn't simplify the axiom as Jie suggested.

**Review by zhengj2007 — COMMENTED** [review]
It seems VEuPathDB import 'medication role' from both OBIB and OGMS. The OBIB one is used in defining 'medication material'. We may consider to fix the issue until OBIB make update.

**Comment by johnwjudkins** [comment]
I could fix it by leaving in the OBIB terms for both 'medication role' and 'medication material' and leaving out the OGMS term until OBIB updates its axiom. @cstoeckert ?

**Comment by cstoeckert** [comment]
I'm OK with sticking with OBIB terms for now until OBIB fixes it.

**Review by cstoeckert — APPROVED** [review]

**Pull request merged**
