### PR TITLE
Make file

### PR DESCRIPTION
**Pull request by zhengj2007**
Add make modules and ROBOT report
Also fix issues for running the ROBOT modules correctly (https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/257)

### CODE REVIEW

**Review by cstoeckert — COMMENTED** [review]
Everything looks good to me in the file diffs but haven't tried to run make yet. Did you want us to do that?

**Comment by zhengj2007** [comment]
> Everything looks good to me in the file diffs but haven't tried to run make yet. Did you want us to do that?

@cstoeckert and @johnwjudkins Would be nice that one of you can test it. Here is the details of make commands, https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/wiki/Make-commands

**Review by johnwjudkins — CHANGES_REQUESTED** [review]
I made a small addition to a definition in a template and ran the make module command. Nothing updated, even when I used the -B flag. (I changed "lighting" to "lightning" in the definition for EUPATH:0000024 in the obsolete template.)

**Comment by zhengj2007** [comment]
@johnwjudkins What changes do you want me to make?

**Comment by johnwjudkins** [comment]
I'm not sure. I only know it's not working yet because the make modules command did not update the module when I changed the associated template.

**Comment by zhengj2007** [comment]
Have you checked the make -B modules. For make modules, if you check the wiki page I wrote, generally it will detect there are changes on the file and make the update but not guarantee. It is kind of depending on the computer. It works for me. You may try to delete one line in the template file and see what happen.

**Comment by johnwjudkins** [comment]
Got it to work - for some reason restarting the terminal on my computer make it work.

**Comment by zhengj2007** [comment]
> Got it to work - for some reason restarting the terminal on my computer make it work.

Great!

**Pull request merged**
