### PR TITLE
update 'alternative term' to 'alternative label'

### LINKED ISSUE #355: OMO annotation conflicting with BFO
@zhengj2007 
OMO in its latest release has replaced 'alternative term' with 'alternative label', conflicting with BFO and other ontologies. (I see no other similar issues.)

This raises 2 issues:

1. Which label do we use? [This](https://github.com/information-artifact-ontology/ontology-metadata/issues/8) suggests it should be 'alternative label'?
2. How do we fix this in the .owl file?

Issue 2 may be solved by replacing the import URL for either BFO or OMO with our own import file (like we do for most import ontologies) in eupath-dev.

### PR DESCRIPTION
**Pull request by johnwjudkins**
Closes #355.

### CODE REVIEW

**Review by zhengj2007 — COMMENTED** [review]
If it is not too hard, I'd like to update the label and definition of term EUPATH_0001021 'VEuPathDB alternative term' from alternative term -> alternative label before merge this request.

**Comment by zhengj2007** [comment]
That's fine to me. If I remember correctly, EUPATH:0001021 was added after the latest release. So, we can remove it and move EUPATH:0000052 out from deprecation template.

Besides, we need to update the displayLabel template, change alternative term -> alternative label too.

**Comment by johnwjudkins** [comment]
The recent commits fixes the IRI and "term" to "label" in annotations (and the date). I have trouble updating the template, so I'm making the fixes in eupath.owl now; I can deal with the template changes after submitting the RC.

**Review by zhengj2007 — APPROVED** [review]
eupath.owl looks good. It can be merged. 

Please update the templates/modules before make github release since it will tag the files for the release. If we don't do it, the source code will not be consistent with the release version.

**Comment by johnwjudkins** [comment]
ROBOT report found errors, which I fixed by updating the organism detection templates/modules and by updating definitions in import_OBI.owl. Some OBI detection data terms I submitted have textual definitions that are corrected in obi-dev, but the corrections have not yet made it to the OBI release. (These textual definitions had "bacteria" for terms about viruses or eukaryota.)

**Comment by zhengj2007** [comment]
It's fine. We can include it in the release notes, indicate the OBI version and specify it as known issues.
> ROBOT report found errors, which I fixed by updating the organism detection templates/modules and by updating definitions in import_OBI.owl. Some OBI detection data terms I submitted have textual definitions that are corrected in obi-dev, but the corrections have not yet made it to the OBI release. (These textual definitions had "bacteria" for terms about viruses or eukaryota.)

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
