### PR TITLE
new Anaplasma terms and update NCBITaxon imports

### LINKED ISSUE #462: NTR: Strains of Anaplasma phagocytophilum
For new term requests, please provide the following information:
**Term Label** [required]
Anaplasma phagocytophilum str. Ap-ha
Anaplasma phagocytophilum str. Ap-v1

**Synonyms** [optional]

**Definition** [required except for organism name]
[Trost et al. (2018)](javascript:;) identified three distinct clades of this intracellular bacterium by sequence divergence in the ankyrin A gene. The two clades that infect humans are known collectively as the Ap-ha strain and the strain that has not been shown to infect humans is known as Ap-v1. The Ap-v1 strain infects deer ([Massung et al. 2005](javascript:;)) and several other animals

https://academic.oup.com/jme/article/56/4/1122/5476390

**Suggested Parent Term** [required]

NCBITaxon_948 in EUPATH

**Examples** [optional]

**Contributor** [optional]
If you would like to be a contributor of the term or anyone you think that contributes to the term, such as label, definition, please provide the name and ORCID ID.

**Requester** [optional]
Please indicate which resource/database/project/ request the term.

### PR DESCRIPTION
**Pull request by johnwjudkins**
Resolves #462.

### CODE REVIEW

**Comment by johnwjudkins** [comment]
Updated to resolve #464.

@SAK22 Please note that these EUPATH IDs have been replaced by recent additions to the NCBITaxon ontology:


Culex inconspicuosus | http://purl.obolibrary.org/obo/EUPATH_0043101 | http://purl.obolibrary.org/obo/NCBITaxon_2918769
-- | -- | --
Mimomyia hispida | http://purl.obolibrary.org/obo/EUPATH_0043108 | http://purl.obolibrary.org/obo/NCBITaxon_2918771
Uranotaenia mashonaensis | http://purl.obolibrary.org/obo/EUPATH_0043113 | http://purl.obolibrary.org/obo/NCBITaxon_487103

**Comment by zhengj2007** [comment]
@johnwjudkins Could you please find the corresponding NTR trackers related to the terms below and added the comments if there is an associated tracker? 
Besides, create a redmine ticket to request the IRI replacements in popBio.owl and assigned to me? Thanks! 

> @SAK22 Please note that these EUPATH IDs have been replaced by recent additions to the NCBITaxon ontology:
> 
> Culex inconspicuosus	http://purl.obolibrary.org/obo/EUPATH_0043101	http://purl.obolibrary.org/obo/NCBITaxon_2918769
> Mimomyia hispida	http://purl.obolibrary.org/obo/EUPATH_0043108	http://purl.obolibrary.org/obo/NCBITaxon_2918771
> Uranotaenia mashonaensis	http://purl.obolibrary.org/obo/EUPATH_0043113	http://purl.obolibrary.org/obo/NCBITaxon_487103

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
Please add the comments in the issue-462 regarding the two terms added in the eupath_dev.owl with their EUPATH_IDs assigned. In the eupath_dev.owl, please add the 'term tracker item', 'dc:contributor', or 'term editor' and 'ontology term requester' (popBio) annotations.

**Comment by johnwjudkins** [comment]
This latest commit adds term tracker item annotations for each organism term with EUPATH ID. I added Sarah as contributor for the Anaplasma terms since she requested them.

**Comment by johnwjudkins** [comment]
One last commit because 'Anopheles nuneztovari sensu lato' was in eupath-dev directly, when it should have been added to the popbio-organism template. 'Anopheles nuneztovari' also belongs under its associated "sensu lato" term.

**Review by zhengj2007 — COMMENTED** [review]
'Anopheles nuneztovari sensu lato' is not in the popbio_organism template yet. Are you planning to move it?

Besides, create a redmine ticket regarding IRI replacement and assign to me. Thanks!

**Comment by johnwjudkins** [comment]
The redmine is assigned. In the last commit, I already added 'Anopheles nuneztovari sensu lato' (EUPATH:0043247) to the popbio_organism template, then I made the module and removed that term from eupath_dev.owl.

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
