### PR TITLE
Mosquito Magnet Liberty Plus trap

### PR DESCRIPTION
**Pull request by johnwjudkins**
#303

@zhengj2007 This adds the term for the upcoming VEuPath release with a EUPATH placeholder ID. I intend to submit this to OBI.

### CODE REVIEW

**Review by zhengj2007 — COMMENTED** [review]
The term will submit to OBI and the IRI will be replaced. So, I'd prefer next to add the term in the coming release. Otherwise, we need to deprecate the term when it be added in the OBI.

**Comment by johnwjudkins** [comment]
@zhengj2007 you're suggesting I should not add this term until it has an OBI ID, correct? I will change this to pending status then.

**Comment by zhengj2007** [comment]
Yes. @johnwjudkins 

> @zhengj2007 you're suggesting I should not add this term until it has an OBI ID, correct? I will change this to pending status then.

Yes @johnwjudkins

**Comment by johnwjudkins** [comment]
This was merged into the OBI development file as OBI:0003454 (so it will be in the next release).

**Comment by johnwjudkins** [comment]
OBI release is out, so these can be imported.

**Pull request merged**
