### PR TITLE
Add VEuPathDB term template

### PR DESCRIPTION
**Pull request by zhengj2007**
Add template that contains only VEuPathDB terms, issue: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/488

### CODE REVIEW

**Comment by johnwjudkins** [comment]
I compared the merged eupath_dev files before and after refactoring (using ROBOT diff). There are differences, but they appear to not be significant (the changes removed some '@en' and 'xsd:string' tags).

**Comment by johnwjudkins** [comment]
@zhengj2007 Ready for review.

**Comment by johnwjudkins** [comment]
@zhengj2007 I just made 2 small changes: adding the missing annotations for the ontology itself (title, description, etc.) and moved one annotation value from EUPATH:0000001 to EUPATH:0000740.

**Comment by johnwjudkins** [comment]
Updated as per discussion. @en tags added to labels and definitions. eupath_dev.owl contains no terms except those it imports from externalByHand and other import/module files.

**Comment by johnwjudkins** [comment]
@zhengj2007 Ready for review.

**Comment by johnwjudkins** [comment]
@zhengj2007 Ready for review. I had to use display names in the axioms template, instead of IDs.

**Comment by zhengj2007** [comment]
@johnwjudkins Most files look good. 

Here are suggested changes:
‘Is about’ is set as both annotation and data property. It may cause by the conversion of template using IDs rather than labels. See: clinical-chemistry-data.owl, many terms declared as dataProperty.

Three templates:
- clinical-chemistry-data.tsv 
- insecticide_resistance.tsv
- Threshold-cycle.tsv 

contains some IDs rather then term labels.
May change to use labels.

‘VEuPathDB alternative label’ is a subPropertyOf ‘alternative label’, can add in axioms.tsv.

assay.tsv does not contain any term. Consider to remove.

insecticide_resistance.tsv
First cell, not wrong, but better improve it by using “Ontology ID"

eupath_dev.owl contains some entity declarations and a GAZ instance. Can remove all of them only keep xml:base, xmlns and owl:ontology sections. 
Following namespace declarations can be removed in the eupath_dev.owl since they are not used by the ontology now.
```
xmlns:protege="http://protege.stanford.edu/plugins/owl/protege#"
xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#"
```

**Comment by johnwjudkins** [comment]
@zhengj2007 All above changes are implemented, except I kept oboInOwl, because it is used by [ObsoleteClass](http://www.geneontology.org/formats/oboInOwl%23ObsoleteClass).

NCBITaxon imports are updated (Giardia label changed).

**Comment by zhengj2007** [comment]
@johnwjudkins All look good to me. I will assign you as reviewer and you can approve and merge the changes. Thanks!

**Pull request merged**
