### PR TITLE
Add term 'parasitemia percentage'

### PR DESCRIPTION
**Pull request by zhengj2007**
Issue: https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/416

### CODE REVIEW

**Comment by johnwjudkins** [comment]
Would it be better, instead of using "percent" or "percentage", to use a more general word like "ratio"?

**Comment by zhengj2007** [comment]
Label: parasitized erythrocyte count to total erythrocyte count ratio

Alternative label: percentage parasitemia 

Definition: A parasitemia measurement in which the number of parasitized erythrocyte is divided by the number of all erythrocyte in a specified sample of blood, and the result presented as a ratio, fraction, quotient or percentage. 
that is expressed as percentage of erythrocytes parasitized.

**Review by johnwjudkins — CHANGES_REQUESTED** [review]
The labels are fine. I made one grammatical change:

A parasitemia measurement in which the number of parasitized erythrocytes is divided by the number of all erythrocytes in a specified sample of blood, and the result presented as a ratio, fraction, quotient or percentage.

(I also don't think the last part of the definition after "blood" is necessary, but we can keep it.)

**Review by johnwjudkins — CHANGES_REQUESTED** [review]
The definition should have "erythrocytes" (plural). See previous comment.

**Review by johnwjudkins — APPROVED** [review]

**Pull request merged**
