### PR TITLE
additional imports

### PR DESCRIPTION
**Pull request by johnwjudkins**
#190

### CODE REVIEW

**Comment by zhengj2007** [comment]
Would like to review when conflicts resolved.

**Comment by johnwjudkins** [comment]
@zhengj2007 It's resolved.

**Comment by zhengj2007** [comment]
@johnwjudkins Would be nice to have more details of the changes you have made in the commit message. So, I can know what I should review. Thanks!

**Comment by zhengj2007** [comment]
Need to import following terms as well, DOID_229, UBERON_0001729, UBERON_0012168

**Comment by johnwjudkins** [comment]
I un-requested the review so I can make additional changes.

**Comment by zhengj2007** [comment]
I just made some changes and will commit.

**Comment by zhengj2007** [comment]
@johnwjudkins It seems you import terms from 6 new ontologies, ARO, DUO, OAE, OBCS, OMIABIS, and ONS. The makefile can only remake the import OWL files when they exist. So, you need to generate the new import OWL file from the ontoFox for the first time. The makefile cannot handle it. Besides, the new import ontologies need to be added in the Makefile since it handle the import OWL file differently when generate the base files.

The OMIABIS is merged to OBIB. So, we should import the OMIABIS terms from OBIB directly. However, if we do so, the terms with OMIABIS prefix will be removed when generate the base file. So, we can import the OMIABIS terms now but need to update when OBIB assign the OMIABIS terms with OBIB prefix. (OMIABIS will bring in the inconsistency, for example, the IAO: definition has two labels, definition and textual definition)

Using OntoFox 'includeComputedIntermediates' import option, may miss some terms. So, need to check after the import.

When import terms from new ontology resources, we need to add the import OWL file IRI in the eupath_dev.owl.

**Review by cstoeckert — CHANGES_REQUESTED** [review]
As discussed, we should not be importing terms directly from OMIABIS. OMIABIS terms belong to OBIB and we should import from there. 
Also, take opportunity to add one more NCBI taxon term NCBITaxon_53535 'Melanoconion' as per #188

**Comment by zhengj2007** [comment]
OMIABIS terms will be removed if we import them from OBIB when generate the base file using the script. May need to import using OntoFox directly.

**Comment by johnwjudkins** [comment]
There are only 2 OMIABIS terms - should I put them in externalByHand? @zhengj2007 @cstoeckert

**Comment by zhengj2007** [comment]
> There are only 2 OMIABIS terms - should I put them in externalByHand? @zhengj2007 @cstoeckert

@johnwjudkins  That sounds good to me.

Besides, there are few OBCS terms in externalByHand.owl. If you can move it to OBCS import file would be great.

**Comment by cstoeckert** [comment]
I agree with Jie.

**Review by cstoeckert — APPROVED** [review]

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
