### PR TITLE
Deprecated most of the terms in the schedule_deprecate template

### PR DESCRIPTION
**Pull request by johnwjudkins**
#166.

I left out of this pull request some classes that maybe should remain in the ontology:

- lesion score classes have subclasses that are not scheduled for deprecation
- 'first respiratory rate measurement datum' is scheduled for deprecation, but 'second respiratory rate measurement datum' is not
- 'host organism' has a subclass that is not scheduled for deprecation
- I left out 'building material role' and its subclasses because they are used to define 'building material' and its subclasses

### CODE REVIEW

**Comment by johnwjudkins** [comment]
I just now merged the other PR, so I may need to adjust this PR accordingly. I'll request review when done.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
For those terms moved from scheduled to deprecate to obsolete, they need to be removed from schedule_deprecate template as well. Otherwise, the term has deprecated 'true' and scheduled_to_deprecate_on_or_after 'yes', e.g. EUPATH_0000353.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
Following four annotation properties were still in schedule_deprecate module but also set deprecated annotation as true in the eupath_dev.owl. 
EUPATH:0000052	EuPathDB alternative term
EUPATH:0000112	EuPathDB definition
EUPATH:0001000	column order
EUPATH:0001007	datafile value

I remember we have decided to obsolete the terms. So, I propose:
1. Remove the terms from the schedule_deprecate template
2. Remove the deprecated setting in the eupath_dev.owl
3. Add the terms in the obsolete template.
4. Add the entity type column (as we did in schedule_deprecate template) and associated the terms with the correct entity type in the template file.

**Review by zhengj2007 — CHANGES_REQUESTED** [review]
4 deprecated object properties, two of them moved in the obsolete OWL with some axioms still leave in the eupath_dev.owl. Two of them are not in the obsolete template. Better to put all deprecate entities with their axioms in the obsolete.owl (need to update the template for this purpose)

Following are axioms specified in the eupath_dev.owl
    

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/EUPATH_0000005">
        <obo:IAO_0000116>no longer in use</obo:IAO_0000116>
        <rdfs:label xml:lang="en">obsolete_material may be used for</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:ObjectProperty>

    

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/EUPATH_0000044">
        <rdfs:label xml:lang="en">obsolete_manifestation of</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:ObjectProperty>
    
    

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/EUPATH_0000060">
        <obo:IAO_0000115>A relation between a medication material and a disease or symptom that it may treat.</obo:IAO_0000115>
        <obo:IAO_0000233>https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/121</obo:IAO_0000233>
        <rdfs:label xml:lang="en">obsolete_may treat</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:ObjectProperty>
    
    

    <owl:ObjectProperty rdf:about="http://purl.obolibrary.org/obo/EUPATH_0000061">
        <obo:IAO_0000115>A relation between a drug product and (one of) its active ingredient.</obo:IAO_0000115>
        <obo:IAO_0100001>http://purl.obolibrary.org/obo/RO_0002248</obo:IAO_0100001>
        <rdfs:label>obsolete_has active ingredient</rdfs:label>
        <owl:deprecated rdf:datatype="http://www.w3.org/2001/XMLSchema#boolean">true</owl:deprecated>
    </owl:ObjectProperty>

**Comment by johnwjudkins** [comment]
@zhengj2007 Did you mean to say annotations, rather than axioms? I added the annotations for the deprecated object properties to the obsolete module and removed them from eupath_dev.

**Comment by zhengj2007** [comment]
I think something like this, <rdfs:label>obsolete_has active ingredient</rdfs:label>, is axiom. We can also say it is the annotations associated with the entity.

**Comment by johnwjudkins** [comment]
I also moved individuals to the obsolete module. That leaves obsolete_core, but that is pulled from OMO and is not in eupath_dev (it also does not have a EUPATH ID).

**Review by zhengj2007 — APPROVED** [review]

**Pull request merged**
